#!/bin/bash

set -x 

# Setup the website directory with the current website
mkdir -p build
cd build
rm -rf ixml website
git clone -b gh-pages https://github.com/invisibleXML/ixml.git
mv ixml website
cd website
rm -rf .git
cd ../../

# Copy the current editors drafts
cp ixml-specification.html build/website/
cp ixml.ixml ixml.xml build/website/

# Format the test catalog
rm -rf build/website/test-catalog
mkdir -p build/website/test-catalog/{css,img}
cp tools/img/* build/website/test-catalog/img/
cp tools/css/* build/website/test-catalog/css/
java -jar tools/Saxon11.3/saxon-he-11.3.jar -s:tests/test-catalog.xml \
     -o:build/website/test-catalog/index.html \
     -xsl:tests/tools/to-html.xsl
